version: '3.8'

services:
    app:
      image: vkfkswjs26/bow-meow:latest
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:8080"
      env_file:
        - .env
      depends_on:
        - db

    db:
        image: postgres:latest
        environment:
          POSTGRES_USERS: shl
          POSTGRES_PASSWORD: greedy
          POSTGRES_DB : bowmeow
        volumes:
          - db-data:/var/lib/postgresql/data
volumes:
  db-data:

