name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t vkfkswjs26/bow-meow-payment:latest .

      - name: Push Docker image
        run: docker push vkfkswjs26/bow-meow-payment:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          script: |
            docker pull vkfkswjs26/bow-meow-payment:latest
            docker stop existing-container || true
            docker rm existing-container || true
            docker run -d --name new-container vkfkswjs26/bow-meow-payment:latest
